= Resource: OGC API Conformance Declaration

Version: 1.0.1

== Description

An OGC API Conformance Declaration lists the conformance classes from standards or community specifications, identified by a URI, that the API conforms to. 

Clients may but are not required to use this information. This resource is intended to support "generic" clients that want to access multiple implementations of OGC API standards - and not "just" a specific API / server. For this purpose, the server can declare the conformance classes it implements and conforms to.

== Path template

`{landingPage}/conformance`

* `{landingPage}` is the URI of the landing page of the API

[[properties]]
== Pre-defined properties

.Properties
[cols="20,10a,70a",options="header"]
!===
|Property |Type |Description
|conformsTo |[ URI ] |**REQUIRED**. The list of URIs of all OGC API conformance classes that the API conforms to. Servers MAY add also URIs of conformance classes that have not been standardized by OGC.
!===

== Representation: JSON 

The JSON representation is the currently recommended representation that all APIs should support.

=== Example

.Conformance declaration example (JSON)
=================
This example is for an API implementing OGC API - Features - Part 1: Core and that supports OpenAPI 3.0 for the API definition and HTML and GeoJSON as encodings for features.

[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson"
  ]
}
----
=================

=== Media type

`application/json`

=== Schema

[source,YAML]
----
include::conformance-declaration.yaml[]
----

== Representation: HTML 

An HTML representation should include all information that is part of the JSON representation.

=== Media type

`text/html`
